In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [46]:
training_data=pd.read_csv('Yes_Bank_Training.csv')
default=training_data

In [47]:
print training_data.head()

   serial_number  age_in_years job_description marital_status  \
0              1            58      management        married   
1              2            44      technician         single   
2              3            33    entrepreneur        married   
3              4            47     blue-collar        married   
4              5            33         unknown         single   

  education_details has_default  balance_in_account housing_status  \
0          tertiary          no                2143            yes   
1         secondary          no                  29            yes   
2         secondary          no                   2            yes   
3           unknown          no                1506            yes   
4           unknown          no                   1             no   

  previous_loan phone_type  date month_of_year  call_duration  \
0            no    unknown     5           may            261   
1            no    unknown     5           may            

In [48]:
training_data = training_data.select_dtypes(include=[object])
training_data.head(3)

job_description marital_status education_details has_default housing_status  \
0      management        married          tertiary          no            yes   
1      technician         single         secondary          no            yes   
2    entrepreneur        married         secondary          no            yes   

  previous_loan phone_type month_of_year poutcome_of_campaign outcome  
0            no    unknown           may              unknown      no  
1            no    unknown           may              unknown      no  
2           yes    unknown           may              unknown      no

In [49]:
training_data.shape

(31649, 10)

In [50]:
from sklearn import preprocessing

In [51]:
training_data.columns

Index([u'job_description', u'marital_status', u'education_details',
       u'has_default', u'housing_status', u'previous_loan', u'phone_type',
       u'month_of_year', u'poutcome_of_campaign', u'outcome'],
      dtype='object')

In [52]:
label_encoder = preprocessing.LabelEncoder()

In [53]:
training_data = training_data.apply(label_encoder.fit_transform)
training_data.head()

job_description  marital_status  education_details  has_default  \
0                4               1                  2            0   
1                9               2                  1            0   
2                2               1                  1            0   
3                1               1                  3            0   
4               11               2                  3            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           2              8   
1               1              0           2              8   
2               1              1           2              8   
3               1              0           2              8   
4               0              0           2              8   

   poutcome_of_campaign  outcome  
0                     3        0  
1                     3        0  
2                     3        0  
3                     3        0  
4                     3        0

In [54]:
training_data['age_in_years']=default['age_in_years']
training_data['balance_in_account']=default['balance_in_account']
training_data['date']=default['date']
training_data['call_duration']=default['call_duration']
training_data['campaign_contacts']=default['campaign_contacts']
training_data['days_passed']=default['days_passed']
training_data['previous_contact']=default['previous_contact']

training_data.head()

job_description  marital_status  education_details  has_default  \
0                4               1                  2            0   
1                9               2                  1            0   
2                2               1                  1            0   
3                1               1                  3            0   
4               11               2                  3            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           2              8   
1               1              0           2              8   
2               1              1           2              8   
3               1              0           2              8   
4               0              0           2              8   

   poutcome_of_campaign  outcome  age_in_years  balance_in_account  date  \
0                     3        0            58                2143     5   
1                     3        0            44                  29     5   
2                     3        0            33                   2     5   
3                     3        0            47                1506     5   
4                     3        0            33                   1     5   

   call_duration  campaign_contacts  days_passed  previous_contact  
0            261                  1           -1                 0  
1            151                  1           -1                 0  
2             76                  1           -1                 0  
3             92                  1           -1                 0  
4            198                  1           -1                 0

In [55]:
test_data=pd.read_csv('Yes_Bank_Test.csv')
default2=test_data

In [56]:
test_data.head()

serial_number  age_in_years job_description marital_status  \
0              1            33          admin.        married   
1              2            40      management        married   
2              3            30      technician         single   
3              4            44     blue-collar        married   
4              5            35      technician        married   

  education_details has_default  balance_in_account housing_status  \
0         secondary          no                 796            yes   
1         secondary          no                 754             no   
2         secondary          no               10152            yes   
3         secondary          no                 545            yes   
4         secondary          no                5553            yes   

  previous_loan phone_type  date month_of_year  call_duration  \
0            no  telephone     6           apr            216   
1           yes   cellular     6           apr            635   
2            no   cellular     6           apr           1108   
3            no   cellular     6           apr            122   
4            no   cellular     6           apr            371   

   campaign_contacts  days_passed  previous_contact poutcome_of_campaign  
0                  1           -1                 0              unknown  
1                  1           -1                 0              unknown  
2                  2          270                 1              failure  
3                  3          136                 1              failure  
4                  3          136                 7              failure

In [57]:
test_data = test_data.select_dtypes(include=[object])
test_data.head(3)

job_description marital_status education_details has_default housing_status  \
0          admin.        married         secondary          no            yes   
1      management        married         secondary          no             no   
2      technician         single         secondary          no            yes   

  previous_loan phone_type month_of_year poutcome_of_campaign  
0            no  telephone           apr              unknown  
1           yes   cellular           apr              unknown  
2            no   cellular           apr              failure

In [58]:
test_data.shape

(13562, 9)

In [59]:
test_data.columns

Index([u'job_description', u'marital_status', u'education_details',
       u'has_default', u'housing_status', u'previous_loan', u'phone_type',
       u'month_of_year', u'poutcome_of_campaign'],
      dtype='object')

In [60]:
label_encoder2 = preprocessing.LabelEncoder()

In [61]:
test_data = test_data.apply(label_encoder2.fit_transform)
test_data.head()

job_description  marital_status  education_details  has_default  \
0                0               1                  1            0   
1                4               1                  1            0   
2                9               2                  1            0   
3                1               1                  1            0   
4                9               1                  1            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           1              0   
1               0              1           0              0   
2               1              0           0              0   
3               1              0           0              0   
4               1              0           0              0   

   poutcome_of_campaign  
0                     3  
1                     3  
2                     0  
3                     0  
4                     0

In [62]:
test_data['age_in_years']=default2['age_in_years']
test_data['balance_in_account']=default2['balance_in_account']
test_data['date']=default2['date']
test_data['call_duration']=default2['call_duration']
test_data['campaign_contacts']=default2['campaign_contacts']
test_data['days_passed']=default2['days_passed']
test_data['previous_contact']=default2['previous_contact']
test_data.head()

job_description  marital_status  education_details  has_default  \
0                0               1                  1            0   
1                4               1                  1            0   
2                9               2                  1            0   
3                1               1                  1            0   
4                9               1                  1            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           1              0   
1               0              1           0              0   
2               1              0           0              0   
3               1              0           0              0   
4               1              0           0              0   

   poutcome_of_campaign  age_in_years  balance_in_account  date  \
0                     3            33                 796     6   
1                     3            40                 754     6   
2                     0            30               10152     6   
3                     0            44                 545     6   
4                     0            35                5553     6   

   call_duration  campaign_contacts  days_passed  previous_contact  
0            216                  1           -1                 0  
1            635                  1           -1                 0  
2           1108                  2          270                 1  
3            122                  3          136                 1  
4            371                  3          136                 7

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,precision_recall_curve
from sklearn.preprocessing import RobustScaler


In [64]:
target_name='outcome'
X=training_data.drop('outcome',axis=1)
robust_scaler=RobustScaler()
X=robust_scaler.fit_transform(X)
y=training_data[target_name]
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=123,stratify=y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

In [65]:
from sklearn.linear_model import LogisticRegression
logistic_regression=LogisticRegression(n_jobs=-1,random_state=15)
logistic_regression.fit(X_train,y_train)
y_pred_test=logistic_regression.predict(X_test)


In [66]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred_test)
confusion_matrix

array([[8826,   99],
       [ 422,  148]])

In [67]:
print y_pred_test

[0 0 0 ... 0 0 0]


In [68]:
y1_pred_test=logistic_regression.predict(test_data)

In [69]:
print y1_pred_test


[1 1 1 ... 1 1 1]


In [70]:
df = pd.DataFrame(y1_pred_test)
df.replace((1, 0),('yes','no'), inplace=True)

df.to_csv("output.csv")

In [71]:
print df


         0
0      yes
1      yes
2      yes
3      yes
4      yes
5      yes
6      yes
7      yes
8      yes
9      yes
10     yes
11     yes
12     yes
13     yes
14     yes
15     yes
16     yes
17     yes
18     yes
19     yes
20     yes
21     yes
22     yes
23     yes
24     yes
25     yes
26     yes
27     yes
28     yes
29     yes
...    ...
13532  yes
13533  yes
13534  yes
13535  yes
13536  yes
13537  yes
13538  yes
13539  yes
13540  yes
13541  yes
13542  yes
13543  yes
13544  yes
13545  yes
13546  yes
13547  yes
13548  yes
13549  yes
13550  yes
13551  yes
13552  yes
13553  yes
13554  yes
13555  yes
13556  yes
13557  yes
13558  yes
13559  yes
13560  yes
13561  yes

[13562 rows x 1 columns]
