In [146]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [147]:
training_data=pd.read_csv('Yes_Bank_Training.csv')


In [148]:
print training_data.head()

   serial_number  age_in_years job_description marital_status  \
0              1            58      management        married   
1              2            44      technician         single   
2              3            33    entrepreneur        married   
3              4            47     blue-collar        married   
4              5            33         unknown         single   

  education_details has_default  balance_in_account housing_status  \
0          tertiary          no                2143            yes   
1         secondary          no                  29            yes   
2         secondary          no                   2            yes   
3           unknown          no                1506            yes   
4           unknown          no                   1             no   

  previous_loan phone_type  date month_of_year  call_duration  \
0            no    unknown     5           may            261   
1            no    unknown     5           may            

In [149]:
training_data = training_data.select_dtypes(include=[object])
training_data.head(3)

job_description marital_status education_details has_default housing_status  \
0      management        married          tertiary          no            yes   
1      technician         single         secondary          no            yes   
2    entrepreneur        married         secondary          no            yes   

  previous_loan phone_type month_of_year poutcome_of_campaign outcome  
0            no    unknown           may              unknown      no  
1            no    unknown           may              unknown      no  
2           yes    unknown           may              unknown      no

In [150]:
training_data.shape

(31649, 10)

In [151]:
from sklearn import preprocessing

In [152]:
training_data.columns

Index([u'job_description', u'marital_status', u'education_details',
       u'has_default', u'housing_status', u'previous_loan', u'phone_type',
       u'month_of_year', u'poutcome_of_campaign', u'outcome'],
      dtype='object')

In [153]:
label_encoder = preprocessing.LabelEncoder()

In [154]:
training_data = training_data.apply(label_encoder.fit_transform)
training_data.head()

job_description  marital_status  education_details  has_default  \
0                4               1                  2            0   
1                9               2                  1            0   
2                2               1                  1            0   
3                1               1                  3            0   
4               11               2                  3            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           2              8   
1               1              0           2              8   
2               1              1           2              8   
3               1              0           2              8   
4               0              0           2              8   

   poutcome_of_campaign  outcome  
0                     3        0  
1                     3        0  
2                     3        0  
3                     3        0  
4                     3        0

In [155]:
training_data.head()

job_description  marital_status  education_details  has_default  \
0                4               1                  2            0   
1                9               2                  1            0   
2                2               1                  1            0   
3                1               1                  3            0   
4               11               2                  3            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           2              8   
1               1              0           2              8   
2               1              1           2              8   
3               1              0           2              8   
4               0              0           2              8   

   poutcome_of_campaign  outcome  
0                     3        0  
1                     3        0  
2                     3        0  
3                     3        0  
4                     3        0

In [156]:
test_data=pd.read_csv('Yes_Bank_Test.csv')

In [157]:
test_data.head()

serial_number  age_in_years job_description marital_status  \
0              1            33          admin.        married   
1              2            40      management        married   
2              3            30      technician         single   
3              4            44     blue-collar        married   
4              5            35      technician        married   

  education_details has_default  balance_in_account housing_status  \
0         secondary          no                 796            yes   
1         secondary          no                 754             no   
2         secondary          no               10152            yes   
3         secondary          no                 545            yes   
4         secondary          no                5553            yes   

  previous_loan phone_type  date month_of_year  call_duration  \
0            no  telephone     6           apr            216   
1           yes   cellular     6           apr            635   
2            no   cellular     6           apr           1108   
3            no   cellular     6           apr            122   
4            no   cellular     6           apr            371   

   campaign_contacts  days_passed  previous_contact poutcome_of_campaign  
0                  1           -1                 0              unknown  
1                  1           -1                 0              unknown  
2                  2          270                 1              failure  
3                  3          136                 1              failure  
4                  3          136                 7              failure

In [158]:
test_data = test_data.select_dtypes(include=[object])
test_data.head(3)

job_description marital_status education_details has_default housing_status  \
0          admin.        married         secondary          no            yes   
1      management        married         secondary          no             no   
2      technician         single         secondary          no            yes   

  previous_loan phone_type month_of_year poutcome_of_campaign  
0            no  telephone           apr              unknown  
1           yes   cellular           apr              unknown  
2            no   cellular           apr              failure

In [159]:
test_data.shape

(13562, 9)

In [160]:
test_data.columns

Index([u'job_description', u'marital_status', u'education_details',
       u'has_default', u'housing_status', u'previous_loan', u'phone_type',
       u'month_of_year', u'poutcome_of_campaign'],
      dtype='object')

In [161]:
label_encoder2 = preprocessing.LabelEncoder()

In [162]:
test_data = default1.apply(label_encoder2.fit_transform)
test_data.head()

job_description  marital_status  education_details  has_default  \
0                0               1                  1            0   
1                4               1                  1            0   
2                9               2                  1            0   
3                1               1                  1            0   
4                9               1                  1            0   

   housing_status  previous_loan  phone_type  month_of_year  \
0               1              0           1              0   
1               0              1           0              0   
2               1              0           0              0   
3               1              0           0              0   
4               1              0           0              0   

   poutcome_of_campaign  
0                     3  
1                     3  
2                     0  
3                     0  
4                     0

In [172]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,precision_recall_curve
from sklearn.preprocessing import RobustScaler


In [173]:
target_name='outcome'
X=training_data.drop('outcome',axis=1)
robust_scaler=RobustScaler()
X=robust_scaler.fit_transform(X)
y=training_data[target_name]
#X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=123,stratify=y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)

In [174]:
from sklearn.linear_model import LogisticRegression
logistic_regression=LogisticRegression(n_jobs=-1,random_state=15)
logistic_regression.fit(X_train,y_train)
y_pred_test=logistic_regression.predict(X_test)


In [176]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred_test)
confusion_matrix

array([[8925,    0],
       [ 570,    0]])

In [178]:
print y_pred_test

[0 0 0 ... 0 0 0]


In [190]:
y1_pred_test=logistic_regression.predict(test_data)

In [194]:
print y1_pred_test


[0 0 0 ... 1 0 1]


In [195]:
df = pd.DataFrame(y1_pred_test)
df.replace((1, 0),('yes','no'), inplace=True)

df.to_csv("output.csv")

In [196]:
print df


         0
0       no
1       no
2       no
3       no
4       no
5       no
6       no
7       no
8       no
9       no
10      no
11      no
12      no
13      no
14      no
15      no
16      no
17      no
18      no
19      no
20      no
21      no
22      no
23      no
24      no
25      no
26      no
27      no
28      no
29      no
...    ...
13532   no
13533  yes
13534  yes
13535  yes
13536  yes
13537  yes
13538  yes
13539  yes
13540   no
13541  yes
13542   no
13543  yes
13544  yes
13545   no
13546  yes
13547  yes
13548  yes
13549  yes
13550   no
13551  yes
13552  yes
13553  yes
13554  yes
13555   no
13556  yes
13557  yes
13558  yes
13559  yes
13560   no
13561  yes

[13562 rows x 1 columns]
